credit1_0001:
    gameText("Programming")
 credit_3b()
 newline()
    gameText("   Shigeharu Umezaki")
 newpage()
    gameText("       Nobuhiro Matsuoka")
 newpage()
    gameText("          Yasuo Okuda")
 newpage()
    gameText("       Toshinori Shimono")
 newpage()
    gameText("         Kouji Yoshida")
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()

credit1_0002:
    gameText("          ")
 credit_3b()
    gameText("Characters")
 credit_3b()
 newline()
    gameText("      Setsu Muraki")
 newpage()
    gameText("        Takeshi Fujimoto")
 newpage()
    gameText("         Kouichi Ogawa")
 newpage()
    gameText("        Takeo Yakushiji")
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()

credit1_0003:
    gameText("        ")
 credit_3b()
    gameText("Sound Effects")
 credit_3b()
 newline()
    gameText("    Kazuhiko Uehara")
 newpage()
    gameText("          Harumi Uekou")
 endstring()