credit2_0000:    
    gameText("   Go for it!  Goemon")
 newline()
    gameText("   ")
 credit_3b()
    gameText(" The Rescue of")
 newline()
    gameText("     Princess Yuki ")
 credit_3b()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()


credit2_0001: 
    gameText("         Staff")
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()


credit2_0002:
    gameText("       ")
 credit_3b()
    gameText("The Boss")
 credit_3b()
 newline()
    gameText("   Shigeharu Umezaki")
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()


credit2_0003:
    gameText("        ")
 credit_3b()
   gameText("Konami")
 credit_3b()
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()


credit2_0004:
    gameText("       ")
 credit_3b()
    gameText("The End")
 credit_3b()
 endstring()
