credit1_0001:
    gameText("-Programming-")
 newline()
    gameText("   Shigeharu Umezaki")
 newpage()
    gameText("       Nobuhiro Matsuoka")
 newpage()
    gameText("          Yasuo Okuda")
 newpage()
    gameText("       Toshinori Shimono")
 newpage()
    gameText("         Kouji Yoshida")
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()

credit1_0002:
    gameText("          ")
    gameText("-Characters-")
 newline()
    gameText("      Setsu Muraki")
 newpage()
    gameText("        Takeshi Fujimoto")
 newpage()
    gameText("         Kouichi Ogawa")
 newpage()
    gameText("        Takeo Yakushiji")
 endstring()
 endstring()
 endstring()
 endstring()
 endstring()

credit1_0003:
    gameText("        ")
    gameText("-Sound Effects-")
 newline()
    gameText("    Kazuhiko Uehara")
 newpage()
    gameText("          Harumi Uekou")
 endstring()